---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: oldflux2
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/VLXMDE/oldflux2.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oldflux2
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: oldflux2
